### PR TITLE
add master branch with upstream eigen packages

### PR DESCRIPTION
**Pull request by NeroBurner**

### CODE REVIEW

**Comment by ruslo** [comment]
Branch `master` is for the "clean" untouched Eigen. We should manage this in a different way, what version do we need?

**Comment by ruslo** [comment]
We have https://github.com/hunter-packages/eigen/pull/6 and https://github.com/hunter-packages/eigen/pull/5, should I close this one now?

**Comment by NeroBurner** [comment]
yes, I extracted the clean untouched Eigen packages into the master branch and then branched the respective hunter_3.3.x versions with out patchset. So yes, I think this branch should also be merged

**Comment by ruslo** [comment]
I think a little more about it and probably "keep master clean" doesn't make a lot of sense in current case since there is no Git upstream remote. `hunter-X.Y.Z` approach looks good, we have "clean" version commit there.

**Comment by NeroBurner** [comment]
I'd keep master to have starting point for the hunter specific branches

**Comment by ruslo** [comment]
> I'd keep master to have starting point for the hunter specific branches

I don't see how it can be useful. If somebody want to create his own branch without hunter patches, then he can start with `hunter-X.Y.Z` and find the "clean" commit. If we need new version we have to create new branch `hunter-X.Y.Z` and cherry-pick all our patches anyway.

**Pull request closed without merging**
